#!/bin/sh
# TODO: only update changed files, e.g. in post-commit hook!?
#  - post-merge: git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD
#  - post-commit: git log --name-only --pretty=format: -n1
#    - Does it include deleted files?

# hook_name="${1:-$(basename $0)}"
# echo "Updating tags via git hook ($hook_name)…" >&2

if [ "$(git config --get my.update-ctags)" != "1" ]; then
  exit 0
fi

mkdir .git/tags_lock 2>/dev/null || {
  echo "ctags: lockfile (.git/tags_lock) exists.. skipping." >&2
  exit 0
}
(
  trap 'rmdir .git/tags_lock' EXIT
  trap '' HUP

  gtags=~/.dotfiles/vim/neobundles/gutentags/plat/unix/update_tags.sh
  if ! [ -f "$gtags" ]; then
    echo "$gtags not found. Skipping." >&2
    exit
  fi

  export CTAGS="-L -"
  git ls-files | "$gtags" -e ctags -t tags -p . >/dev/null
) &
