#!/bin/sh
# Git hook to display last commit information when switching branches.

# prev_head=$1
# new_head=$2
# changing_branch=$3

is_clone=0
if [ "$3" = 1 ]; then
  if [ "$1" = "0000000000000000000000000000000000000000" ]; then
    is_clone=1
    prog="$(ps -p $(ps -p "$PPID" -o ppid=) -o comm=)"
    # if [ "${PWD#/tmp/pacaurtmp}" != "$PWD" ]; then
    if [ "$prog" = "pacaur" ]; then
      exit
    fi
  fi
else
  # Checking out a file.
  .git/hooks/ctags post-checkout &
  exit
fi

# Special template/display for "pip" cloning/checking out a VCS URL.
if [ -z "$prog" ]; then
  prog="$(ps -p $(ps -p "$PPID" -o ppid=) -o comm=)"
fi
if [ "$prog" = 'pip' ]; then
  # Get "git" command from 2nd "args" entry of git parent process.
  # TODO: move to clone block above?  / use is_clone flag for pip.
  mode=$(ps -f -p $PPID -o args= | cut -f2 -d\ )
  if [ "$mode" = checkout ]; then  # "checkout" might follow "clone".
    git --no-pager log -1 --pretty=format:"%C(green) checkout: $(basename "$PWD"): %C(blue)%s%C(reset) (%cr, %h, %cN)"
  else
    git --no-pager log -1 --pretty=format:"%C(green)pip-$mode: $(basename "$PWD"): %C(blue)%s%C(reset) (%cr, %h, %cN)"
  fi

else
  git --no-pager log -1 --pretty=format:"Last commit: %C(blue)%s%C(reset) (%cr, %h, %cN)"
  .git/hooks/ctags post-checkout &
fi
# Note: --no-pager does not add a newline.
echo

